name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-first-step
        run: echo "Hello World!"

      - name: my-second-step
        run: echo "Hello ,World!"